import Head from 'next/head';
import Link from 'next/link';
import { Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';

const inter = Inter({ subsets: ['latin'] });

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        Hello world!
        <div>
          See my <Link href="/resume">Resume</Link>
        </div>
        <div>
          See my Blog:
          <ul>
            <li>
              <Link href="/blog/1-static-blog-entry">Static</Link>
            </li>
            <li>
              <Link href="/blog/2-dynamic-blog-entry">Dynamic</Link>
            </li>
          </ul>
        </div>
      </main>
    </>
  );
};

export default Home;
